# CARC (Claim Adjustment Reason Code) lookup table
# Source: X12 official CARC list
# https://x12.org/codes/claim-adjustment-reason-codes

CARC_CODES = {
    "1": "Deductible Amount.",
    "2": "Coinsurance Amount.",
    "3": "Co-payment Amount.",
    "4": "The procedure code is inconsistent with the modifier used.",
    "5": "The procedure code/type of bill is inconsistent with the place of service.",
    "6": "The procedure/revenue code is inconsistent with the patient's age.",
    "7": "The procedure/revenue code is inconsistent with the patient's gender.",
    "8": "The procedure code is inconsistent with the provider type/specialty (taxonomy).",
    "9": "The diagnosis is inconsistent with the patient's age.",
    "10": "The diagnosis is inconsistent with the patient's gender.",
    "11": "The diagnosis is inconsistent with the procedure.",
    "12": "The diagnosis is inconsistent with the provider type.",
    "13": "The date of death precedes the date of service.",
    "14": "The date of birth follows the date of service.",
    "16": "Claim/service lacks information or has submission/billing error(s).",
    "18": "Exact duplicate claim/service.",
    "19": "This is a work-related injury/illness and thus the liability of the Worker's Compensation Carrier.",
    "20": "This injury/illness is covered by the liability carrier.",
    "21": "This injury/illness is the liability of the no-fault carrier.",
    "22": "This care may be covered by another payer per coordination of benefits.",
    "23": "The impact of prior payer(s) adjudication including payments and/or adjustments.",
    "24": "Charges are covered under a capitation agreement/managed care plan.",
    "26": "Expenses incurred prior to coverage.",
    "27": "Expenses incurred after coverage terminated.",
    "29": "The time limit for filing has expired.",
    "31": "Patient cannot be identified as our insured.",
    "32": "Our records indicate the patient is not an eligible dependent.",
    "33": "Insured has no dependent coverage.",
    "34": "Insured has no coverage for newborns.",
    "35": "Lifetime benefit maximum has been reached.",
    "39": "Services denied at the time authorization/pre-certification was requested.",
    "40": "Charges do not meet qualifications for emergent/urgent care.",
    "44": "Prompt-pay discount.",
    "45": "Charge exceeds fee schedule/maximum allowable or contracted/legislated fee arrangement.",
    "49": "This is a non-covered service because it is a routine/preventive exam or a diagnostic/screening procedure done in conjunction with a routine/preventive exam.",
    "50": "These are non-covered services because this is not deemed a 'medical necessity' by the payer.",
    "51": "These are non-covered services because this is a pre-existing condition.",
    "53": "Services by an immediate relative or a member of the same household are not covered.",
    "54": "Multiple physicians/assistants are not covered in this case.",
    "55": "Procedure/treatment/drug is deemed experimental/investigational by the payer.",
    "56": "Procedure/treatment has not been deemed 'proven to be effective' by the payer.",
    "58": "Treatment was deemed by the payer to have been rendered in an inappropriate or invalid place of service.",
    "59": "Processed based on multiple or concurrent procedure rules.",
    "60": "Charges for outpatient services are not covered when performed within a period of time prior to or after inpatient services.",
    "61": "Adjusted for failure to obtain second surgical opinion.",
    "66": "Blood Deductible.",
    "69": "Day outlier amount.",
    "70": "Cost outlier - Adjustment to compensate for additional costs.",
    "74": "Indirect Medical Education Adjustment.",
    "75": "Direct Medical Education Adjustment.",
    "76": "Disproportionate Share Adjustment.",
    "78": "Non-Covered days/Room charge adjustment.",
    "85": "Patient Interest Adjustment (Use Only Group code PR).",
    "89": "Professional fees removed from charges.",
    "90": "Ingredient cost adjustment.",
    "91": "Dispensing fee adjustment.",
    "94": "Processed in Excess of charges.",
    "95": "Plan procedures not followed.",
    "96": "Non-covered charge(s).",
    "97": "The benefit for this service is included in the payment/allowance for another service/procedure that has already been adjudicated.",
    "100": "Payment made to patient/insured/responsible party.",
    "101": "Predetermination: anticipated payment upon completion of services or claim adjudication.",
    "102": "Major Medical Adjustment.",
    "103": "Provider promotional discount (e.g., Senior citizen discount).",
    "104": "Managed care withholding.",
    "105": "Tax withholding.",
    "106": "Patient payment option/election not in effect.",
    "107": "The related or qualifying claim/service was not identified on this claim.",
    "108": "Rent/purchase guidelines were not met.",
    "109": "Claim/service not covered by this payer/contractor. You must send the claim/service to the correct payer/contractor.",
    "110": "Billing date predates service date.",
    "111": "Not covered unless the provider accepts assignment.",
    "112": "Service not furnished directly to the patient and/or not documented.",
    "114": "Procedure/product not approved by the Food and Drug Administration.",
    "115": "Procedure postponed, canceled, or delayed.",
    "116": "The advance indemnification notice signed by the patient did not comply with requirements.",
    "117": "Transportation is only covered to the closest facility that can provide the necessary care.",
    "118": "ESRD network support adjustment.",
    "119": "Benefit maximum for this time period or occurrence has been reached.",
    "121": "Indemnification adjustment - compensation for outstanding member responsibility.",
    "122": "Psychiatric reduction.",
    "128": "Newborn's services are covered in the mother's Allowance.",
    "129": "Prior processing information appears incorrect.",
    "130": "Claim submission fee.",
    "131": "Claim specific negotiated discount.",
    "132": "Prearranged demonstration project adjustment.",
    "133": "The disposition of this service line is pending further review.",
    "134": "Technical fees removed from charges.",
    "135": "Interim bills cannot be processed.",
    "136": "Failure to follow prior payer's coverage rules.",
    "137": "Regulatory Surcharges, Assessments, Allowances or Health Related Taxes.",
    "139": "Contracted funding agreement - Subscriber is employed by the provider of services.",
    "140": "Patient/Insured health identification number and name do not match.",
    "142": "Monthly Medicaid patient liability amount.",
    "143": "Portion of payment deferred.",
    "144": "Incentive adjustment, e.g. preferred product/service.",
    "146": "Diagnosis was invalid for the date(s) of service reported.",
    "147": "Provider contracted/negotiated rate expired or not on file.",
    "148": "Information from another provider was not provided or was insufficient/incomplete.",
    "149": "Lifetime benefit maximum has been reached for this service/benefit category.",
    "150": "Payer deems the information submitted does not support this level of service.",
    "151": "Payment adjusted because the payer deems the information submitted does not support this many/frequency of services.",
    "152": "Payer deems the information submitted does not support this length of service.",
    "153": "Payer deems the information submitted does not support this dosage.",
    "154": "Payer deems the information submitted does not support this day's supply.",
    "155": "Patient refused the service/procedure.",
    "157": "Service/procedure was provided as a result of an act of war.",
    "158": "Service/procedure was provided outside of the United States.",
    "159": "Service/procedure was provided as a result of terrorism.",
    "160": "Injury/illness was the result of an activity that is a benefit exclusion.",
    "161": "Provider performance bonus.",
    "163": "Attachment/other documentation referenced on the claim was not received.",
    "164": "Attachment/other documentation referenced on the claim was not received in a timely fashion.",
    "166": "These services were submitted after this payer's responsibility for processing claims under this plan ended.",
    "167": "This diagnosis is not covered.",
    "169": "Alternate benefit has been provided.",
    "170": "Payment is denied when performed/billed by this type of provider.",
    "171": "Payment is denied when performed/billed by this type of provider in this type of facility.",
    "172": "Payment is adjusted when performed/billed by a provider of this specialty.",
    "173": "Service/equipment was not prescribed by a physician.",
    "174": "Service was not prescribed prior to delivery.",
    "175": "Prescription is incomplete.",
    "176": "Prescription is not current.",
    "177": "Patient has not met the required eligibility requirements.",
    "178": "Patient has not met the required spend down requirements.",
    "179": "Patient has not met the required waiting requirements.",
    "180": "Patient has not met the required residency requirements.",
    "181": "Procedure code was invalid on the date of service.",
    "182": "Procedure modifier was invalid on the date of service.",
    "183": "The referring provider is not eligible to refer the service billed.",
    "184": "The prescribing/ordering provider is not eligible to prescribe/order the service billed.",
    "185": "The rendering provider is not eligible to perform the service billed.",
    "186": "Level of care change adjustment.",
    "187": "Consumer Spending Account payments.",
    "188": "This product/procedure is only covered when used according to FDA recommendations.",
    "189": "'Not otherwise classified' or 'unlisted' procedure code was billed when there is a specific procedure code for this procedure/service.",
    "190": "Payment is included in the allowance for a Skilled Nursing Facility (SNF) qualified stay.",
    "192": "Non standard adjustment code from paper remittance.",
    "193": "Original payment decision is being maintained. Upon review, it was determined that this claim was processed properly.",
    "194": "Anesthesia performed by the operating physician, the assistant surgeon or the attending physician.",
    "195": "Refund issued to an erroneous priority payer for this claim/service.",
    "197": "Precertification/authorization/notification/pre-treatment absent.",
    "198": "Precertification/notification/authorization/pre-treatment exceeded.",
    "199": "Revenue code and Procedure code do not match.",
    "200": "Expenses incurred during lapse in coverage.",
    "201": "Patient is responsible for amount of this claim/service through 'set aside arrangement' or other agreement.",
    "202": "Non-covered personal comfort or convenience services.",
    "203": "Discontinued or reduced service.",
    "204": "This service/equipment/drug is not covered under the patient's current benefit plan.",
    "205": "Pharmacy discount card processing fee.",
    "206": "National Provider Identifier - missing.",
    "207": "National Provider identifier - Invalid format.",
    "208": "National Provider Identifier - Not matched.",
    "209": "Per regulatory or other agreement. The provider cannot collect this amount from the patient.",
    "210": "Payment adjusted because pre-certification/authorization not received in a timely fashion.",
    "211": "National Drug Codes (NDC) not eligible for rebate, are not covered.",
    "212": "Administrative surcharges are not covered.",
    "213": "Non-compliance with the physician self referral prohibition legislation or payer policy.",
    "215": "Based on subrogation of a third party settlement.",
    "216": "Based on the findings of a review organization or the payer's findings.",
    "219": "Based on extent of injury.",
    "222": "Exceeds the contracted maximum number of hours/days/units by this provider for this period.",
    "223": "Adjustment code for mandated federal, state or local law/regulation.",
    "224": "Patient identification compromised by identity theft.",
    "226": "Information requested from the Billing/Rendering Provider was not provided or not provided timely or was insufficient/incomplete.",
    "227": "Information requested from the patient/insured/responsible party was not provided or was insufficient/incomplete.",
    "228": "Denied for failure of this provider, another provider or the subscriber to supply requested information to a previous payer for their adjudication.",
    "231": "Mutually exclusive procedures cannot be done in the same day/setting.",
    "232": "Institutional Transfer Amount.",
    "233": "Services/charges related to the treatment of a hospital-acquired condition or preventable medical error.",
    "234": "This procedure is not paid separately.",
    "235": "Sales Tax.",
    "236": "This procedure or procedure/modifier combination is not compatible with another procedure or procedure/modifier combination provided on the same day.",
    "237": "Legislated/Regulatory Penalty.",
    "238": "Claim spans eligible and ineligible periods of coverage, this is the reduction for the ineligible period.",
    "239": "Claim spans eligible and ineligible periods of coverage. Rebill separate claims.",
    "240": "The diagnosis is inconsistent with the patient's birth weight.",
    "241": "Low Income Subsidy (LIS) Co-payment Amount.",
    "242": "Services not provided by network/primary care providers.",
    "243": "Services not authorized by network/primary care providers.",
    "245": "Provider performance program withhold.",
    "246": "This non-payable code is for required reporting only.",
    "247": "Deductible for Professional service rendered in an Institutional setting and billed on an Institutional claim.",
    "248": "Coinsurance for Professional service rendered in an Institutional setting and billed on an Institutional claim.",
    "249": "This claim has been identified as a readmission.",
    "250": "The attachment/other documentation that was received was the incorrect attachment/document.",
    "251": "The attachment/other documentation that was received was incomplete or deficient.",
    "252": "An attachment/other documentation is required to adjudicate this claim/service.",
    "253": "Sequestration - reduction in federal payment.",
    "254": "Claim received by the dental plan, but benefits not available under this plan.",
    "256": "Service not payable per managed care contract.",
    "258": "Claim/service not covered when patient is in custody/incarcerated.",
    "261": "The procedure or service is inconsistent with the patient's history.",
    "272": "Coverage/program guidelines were not met.",
    "273": "Coverage/program guidelines were exceeded.",
    "274": "Fee/Service not payable per patient Care Coordination arrangement.",
    "275": "Prior payer's patient responsibility not covered.",
    "276": "Services denied by the prior payer(s) are not covered by this payer.",
    "279": "Services not provided by Preferred network providers.",
    "281": "Deductible waived per contractual agreement.",
    "282": "The procedure/revenue code is inconsistent with the type of bill.",
    "283": "Attending provider is not eligible to provide direction of care.",
    "284": "Precertification/authorization/notification/pre-treatment number may be valid but does not apply to the billed services.",
    "285": "Appeal procedures not followed.",
    "286": "Appeal time limits not met.",
    "287": "Referral exceeded.",
    "288": "Referral absent.",
    "295": "Pharmacy Direct/Indirect Remuneration (DIR).",
    "299": "The billing provider is not eligible to receive payment for the service billed.",
    "302": "Precertification/notification/authorization/pre-treatment time limit has expired.",
    "A0": "Patient refund amount.",
    "A1": "Claim/Service denied.",
    "A5": "Medicare Claim PPS Capital Cost Outlier Amount.",
    "A6": "Prior hospitalization or 30 day transfer requirement not met.",
    "A8": "Ungroupable DRG.",
    "B1": "Non-covered visits.",
    "B4": "Late filing penalty.",
    "B7": "This provider was not certified/eligible to be paid for this procedure/service on this date of service.",
    "B8": "Alternative services were available, and should have been utilized.",
    "B9": "Patient is enrolled in a Hospice.",
    "B10": "Allowed amount has been reduced because a component of the basic procedure/test was paid.",
    "B11": "The claim/service has been transferred to the proper payer/processor for processing.",
    "B12": "Services not documented in patient's medical records.",
    "B13": "Previously paid.",
    "B14": "Only one visit or consultation per physician per day is covered.",
    "B15": "This service/procedure requires that a qualifying service/procedure be received and covered.",
    "B16": "'New Patient' qualifications were not met.",
    "B20": "Procedure/service was partially or fully furnished by another provider.",
    "B22": "This payment is adjusted based on the diagnosis.",
    "B23": "Procedure billed is not authorized per your Clinical Laboratory Improvement Amendment (CLIA) proficiency test.",
}

# RARC (Remittance Advice Remark Code) lookup table
# Source: X12 official RARC list
# https://x12.org/codes/remittance-advice-remark-codes

RARC_CODES = {
    "M1": "X-ray not taken within the past 12 months or near enough to the start of treatment.",
    "M2": "Not paid separately when the patient is an inpatient.",
    "M3": "Equipment is the same or similar to equipment already being used.",
    "M4": "Alert: This is the last monthly installment payment for this durable medical equipment.",
    "M5": "Monthly rental payments can continue until the earlier of the 15th month from the first rental month, or the month when the equipment is no longer needed.",
    "M6": "Alert: You must furnish and service this item for any period of medical need for the remainder of the reasonable useful lifetime of the equipment.",
    "M7": "No rental payments after the item is purchased, returned or after the total of issued rental payments equals the purchase price.",
    "M8": "We do not accept blood gas tests results when the test was conducted by a medical supplier or taken while the patient is on oxygen.",
    "M9": "Alert: This is the tenth rental month. You must offer the patient the choice of changing the rental to a purchase agreement.",
    "M10": "Equipment purchases are limited to the first or the tenth month of medical necessity.",
    "M11": "DME, orthotics and prosthetics must be billed to the DME carrier who services the patient's zip code.",
    "M12": "Diagnostic tests performed by a physician must indicate whether purchased services are included on the claim.",
    "M13": "Only one initial visit is covered per specialty per medical group.",
    "M14": "No separate payment for an injection administered during an office visit, and no payment for a full office visit if the patient only received an injection.",
    "M15": "Separately billed services/tests have been bundled as they are considered components of the same procedure. Separate payment is not allowed.",
    "M16": "Alert: Please see our web site, mailings, or bulletins for more details concerning this policy/procedure/decision.",
    "M17": "Alert: Payment approved as you did not know, and could not reasonably have been expected to know, that this would not normally have been covered for this patient.",
    "M18": "Certain services may be approved for home use. Neither a hospital nor a Skilled Nursing Facility (SNF) is considered to be a patient's home.",
    "M19": "Missing oxygen certification/re-certification.",
    "M20": "Missing/incomplete/invalid HCPCS.",
    "M21": "Missing/incomplete/invalid place of residence for this service/item provided in a home.",
    "M22": "Missing/incomplete/invalid number of miles traveled.",
    "M23": "Missing invoice.",
    "M24": "Missing/incomplete/invalid number of doses per vial.",
    "M25": "The information furnished does not substantiate the need for this level of service.",
    "M26": "The information furnished does not substantiate the need for this level of service. Refund requirements apply.",
    "M27": "Alert: The patient has been relieved of liability of payment of these items and services under the limitation of liability provision of the law.",
    "M28": "This does not qualify for payment under Part B when Part A coverage is exhausted or not otherwise available.",
    "M29": "Missing operative note/report.",
    "M30": "Missing pathology report.",
    "M31": "Missing radiology report.",
    "M32": "Alert: This is a conditional payment made pending a decision on this service by the patient's primary payer.",
    "M36": "This is the 11th rental month. We cannot pay for this until you indicate that the patient has been given the option of changing the rental to a purchase.",
    "M37": "Not covered when the patient is under age 35.",
    "M38": "Alert: The patient is liable for the charges for this service as they were informed in writing before the service was furnished that we would not pay for it.",
    "M39": "Alert: The patient is not liable for payment of this service as the advance notice of non-coverage you provided the patient did not comply with program requirements.",
    "M40": "Claim must be assigned and must be filed by the practitioner's employer.",
    "M41": "We do not pay for this as the patient has no legal obligation to pay for this.",
    "M42": "The medical necessity form must be personally signed by the attending physician.",
    "M44": "Missing/incomplete/invalid condition code.",
    "M45": "Missing/incomplete/invalid occurrence code(s).",
    "M46": "Missing/incomplete/invalid occurrence span code(s).",
    "M47": "Missing/incomplete/invalid Payer Claim Control Number.",
    "M49": "Missing/incomplete/invalid value code(s) or amount(s).",
    "M50": "Missing/incomplete/invalid revenue code(s).",
    "M51": "Missing/incomplete/invalid procedure code(s).",
    "M52": "Missing/incomplete/invalid 'from' date(s) of service.",
    "M53": "Missing/incomplete/invalid days or units of service.",
    "M54": "Missing/incomplete/invalid total charges.",
    "M55": "We do not pay for self-administered anti-emetic drugs that are not administered with a covered oral anti-cancer drug.",
    "M56": "Missing/incomplete/invalid payer identifier.",
    "M59": "Missing/incomplete/invalid 'to' date(s) of service.",
    "M60": "Missing Certificate of Medical Necessity.",
    "M61": "We cannot pay for this as the approval period for the FDA clinical trial has expired.",
    "M62": "Missing/incomplete/invalid treatment authorization code.",
    "M64": "Missing/incomplete/invalid other diagnosis.",
    "M65": "One interpreting physician charge can be submitted per claim when a purchased diagnostic test is indicated.",
    "M66": "Our records indicate that you billed diagnostic tests subject to price limitations and the procedure code submitted includes a professional component.",
    "M67": "Missing/incomplete/invalid other procedure code(s).",
    "M69": "Paid at the regular rate as you did not submit documentation to justify the modified procedure code.",
    "M70": "Alert: The NDC code submitted for this service was translated to a HCPCS code for processing.",
    "M71": "Total payment reduced due to overlap of tests billed.",
    "M73": "The HPSA/Physician Scarcity bonus can only be paid on the professional component of this service.",
    "M74": "This service does not qualify for a HPSA/Physician Scarcity bonus payment.",
    "M75": "Multiple automated multichannel tests performed on the same day combined for payment.",
    "M76": "Missing/incomplete/invalid diagnosis or condition.",
    "M77": "Missing/incomplete/invalid/inappropriate place of service.",
    "M79": "Missing/incomplete/invalid charge.",
    "M80": "Not covered when performed during the same session/date as a previously processed service for the patient.",
    "M81": "You are required to code to the highest level of specificity.",
    "M82": "Service is not covered when patient is under age 50.",
    "M83": "Service is not covered unless the patient is classified as at high risk.",
    "M84": "Medical code sets used must be the codes in effect at the time of service.",
    "M85": "Subjected to review of physician evaluation and management services.",
    "M86": "Service denied because payment already made for same/similar procedure within set time frame.",
    "M87": "Claim/service(s) subjected to CFO-CAP prepayment review.",
    "M89": "Not covered more than once under age 40.",
    "M90": "Not covered more than once in a 12 month period.",
    "M91": "Lab procedures with different CLIA certification numbers must be billed on separate claims.",
    "M93": "Information supplied supports a break in therapy. A new capped rental period began with delivery of this equipment.",
    "M94": "Information supplied does not support a break in therapy. A new capped rental period will not begin.",
    "M95": "Services subjected to Home Health Initiative medical review/cost report audit.",
    "M96": "The technical component of a service furnished to an inpatient may only be billed by that inpatient facility.",
    "M97": "Not paid to practitioner when provided to patient in this place of service. Payment included in the reimbursement issued the facility.",
    "M99": "Missing/incomplete/invalid Universal Product Number/Serial Number.",
    "M100": "We do not pay for an oral anti-emetic drug that is not administered for use immediately before, at, or within 48 hours of administration of a covered chemotherapy drug.",
    "M102": "Service not performed on equipment approved by the FDA for this purpose.",
    "M103": "Information supplied supports a break in therapy. However, the medical information we have for this patient does not support the need for this item as billed.",
    "M104": "Information supplied supports a break in therapy. A new capped rental period will begin with delivery of the equipment.",
    "M105": "Information supplied does not support a break in therapy. The medical information we have for this patient does not support the need for this item as billed.",
    "M107": "Payment reduced as 90-day rolling average hematocrit for ESRD patient exceeded 36.5%.",
    "M109": "We have provided you with a bundled payment for a teleconsultation. You must send 25 percent of the teleconsultation payment to the referring practitioner.",
    "M111": "We do not pay for chiropractic manipulative treatment when the patient refuses to have an x-ray taken.",
    "M112": "Reimbursement for this item is based on the single payment amount required under the DMEPOS Competitive Bidding Program for the area where the patient resides.",
    "M113": "Our records indicate that this patient began using this item/service prior to the current contract period for the DMEPOS Competitive Bidding Program.",
    "M114": "This service was processed in accordance with rules and guidelines under the DMEPOS Competitive Bidding Program or a Demonstration Project.",
    "M115": "This item is denied when provided to this patient by a non-contract or non-demonstration supplier.",
    "M116": "Processed under a demonstration project or program. Project or program is ending and additional services may not be paid under this project or program.",
    "M117": "Not covered unless submitted via electronic claim.",
    "M119": "Missing/incomplete/invalid/deactivated/withdrawn National Drug Code (NDC).",
    "M121": "We pay for this service only when performed with a covered cryosurgical ablation.",
    "M122": "Missing/incomplete/invalid level of subluxation.",
    "M123": "Missing/incomplete/invalid name, strength, or dosage of the drug furnished.",
    "M124": "Missing indication of whether the patient owns the equipment that requires the part or supply.",
    "M125": "Missing/incomplete/invalid information on the period of time for which the service/supply/equipment will be needed.",
    "M126": "Missing/incomplete/invalid individual lab codes included in the test.",
    "M127": "Missing patient medical record for this service.",
    "M129": "Missing/incomplete/invalid indicator of x-ray availability for review.",
    "M130": "Missing invoice or statement certifying the actual cost of the lens, less discounts, and/or the type of intraocular lens used.",
    "M131": "Missing physician financial relationship form.",
    "M132": "Missing pacemaker registration form.",
    "M133": "Claim did not identify who performed the purchased diagnostic test or the amount you were charged for the test.",
    "M134": "Performed by a facility/supplier in which the provider has a financial interest.",
    "M135": "Missing/incomplete/invalid plan of treatment.",
    "M136": "Missing/incomplete/invalid indication that the service was supervised or evaluated by a physician.",
    "M137": "Part B coinsurance under a demonstration project or pilot program.",
    "M138": "Patient identified as a demonstration participant but the patient was not enrolled in the demonstration at the time services were rendered.",
    "M139": "Denied services exceed the coverage limit for the demonstration.",
    "M141": "Missing physician certified plan of care.",
    "M142": "Missing American Diabetes Association Certificate of Recognition.",
    "M143": "The provider must update license information with the payer.",
    "M144": "Pre-/post-operative care payment is included in the allowance for the surgery/procedure.",
    "MA01": "Alert: If you do not agree with what we approved for these services, you may appeal our decision. You must write to us within 120 days of the date you received this notice.",
    "MA02": "Alert: If you do not agree with this determination, you have the right to appeal. You must file a written request for an appeal within 180 days of the date you receive this notice.",
    "MA04": "Secondary payment cannot be considered without the identity of or payment information from the primary payer. The information was either not reported or was illegible.",
    "MA07": "Alert: The claim information has also been forwarded to Medicaid for review.",
    "MA08": "Alert: Claim information was not forwarded because the supplemental coverage is not with a Medigap plan, or you do not participate in Medicare.",
    "MA09": "Alert: Claim submitted as unassigned but processed as assigned in accordance with our current assignment/participation agreement.",
    "MA10": "Alert: The patient's payment was in excess of the amount owed. You must refund the overpayment to the patient.",
    "MA12": "You have not established that you have the right under the law to bill for services furnished by the person(s) that furnished this service.",
    "MA13": "Alert: You may be subject to penalties if you bill the patient for amounts not reported with the PR (patient responsibility) group code.",
    "MA14": "Alert: The patient is a member of an employer-sponsored prepaid health plan. Services from outside that health plan are not covered.",
    "MA15": "Alert: Your claim has been separated to expedite handling. You will receive a separate notice for the other services reported.",
    "MA16": "The patient is covered by the Black Lung Program.",
    "MA17": "We are the primary payer and have paid at the primary rate. You must contact the patient's other insurer to refund any excess it may have paid.",
    "MA18": "Alert: The claim information is also being forwarded to the patient's supplemental insurer. Send any questions regarding supplemental benefits to them.",
    "MA19": "Alert: Information was not sent to the Medigap insurer due to incorrect/invalid information you submitted concerning that insurer.",
    "MA20": "Skilled Nursing Facility (SNF) stay not covered when care is primarily related to the use of an urethral catheter for convenience or the control of incontinence.",
    "MA21": "SSA records indicate mismatch with name and sex.",
    "MA22": "Payment of less than $1.00 suppressed.",
    "MA23": "Demand bill approved as result of medical review.",
    "MA24": "Christian Science Sanitarium/Skilled Nursing Facility (SNF) bill in the same benefit period.",
    "MA25": "A patient may not elect to change a hospice provider more than once in a benefit period.",
    "MA26": "Alert: Our records indicate that you were previously informed of this rule.",
    "MA27": "Missing/incomplete/invalid entitlement number or name shown on the claim.",
    "MA28": "Alert: Receipt of this notice by a physician or supplier who did not accept assignment is for information only.",
    "MA30": "Missing/incomplete/invalid type of bill.",
    "MA31": "Missing/incomplete/invalid beginning and ending dates of the period billed.",
    "MA32": "Missing/incomplete/invalid number of covered days during the billing period.",
    "MA33": "Missing/incomplete/invalid non-covered days during the billing period.",
    "MA34": "Missing/incomplete/invalid number of coinsurance days during the billing period.",
    "MA35": "Missing/incomplete/invalid number of lifetime reserve days.",
    "MA36": "Missing/incomplete/invalid patient name.",
    "MA37": "Missing/incomplete/invalid patient's address.",
    "MA39": "Missing/incomplete/invalid gender.",
    "MA40": "Missing/incomplete/invalid admission date.",
    "MA41": "Missing/incomplete/invalid admission type.",
    "MA42": "Missing/incomplete/invalid admission source.",
    "MA43": "Missing/incomplete/invalid patient status.",
    "MA44": "Alert: No appeal rights. Adjudicative decision based on law.",
    "MA45": "Alert: As previously advised, a portion or all of your payment is being held in a special account.",
    "MA46": "Alert: The new information was considered but additional payment will not be issued.",
    "MA47": "Our records show you have opted out of Medicare, agreeing with the patient not to bill Medicare for services/tests/supplies furnished. The patient is responsible for payment.",
    "MA48": "Missing/incomplete/invalid name or address of responsible party or primary payer.",
    "MA50": "Missing/incomplete/invalid Investigational Device Exemption number or Clinical Trial number.",
    "MA53": "Missing/incomplete/invalid Competitive Bidding Demonstration Project identification.",
    "MA54": "Physician certification or election consent for hospice care not received timely.",
    "MA55": "Not covered as patient received medical health care services, automatically revoking his/her election to receive religious non-medical health care services.",
    "MA56": "Our records show you have opted out of Medicare. The patient is responsible for payment but you cannot charge the patient more than the limiting charge amount.",
    "MA57": "Patient submitted written request to revoke his/her election for religious non-medical health care services.",
    "MA58": "Missing/incomplete/invalid release of information indicator.",
    "MA59": "Alert: The patient overpaid you for these services. You must issue the patient a refund within 30 days.",
    "MA60": "Missing/incomplete/invalid patient relationship to insured.",
    "MA61": "Missing/incomplete/invalid social security number.",
    "MA62": "Alert: This is a telephone review decision.",
    "MA63": "Missing/incomplete/invalid principal diagnosis.",
    "MA64": "Our records indicate that we should be the third payer for this claim.",
    "MA65": "Missing/incomplete/invalid admitting diagnosis.",
    "MA66": "Missing/incomplete/invalid principal procedure code.",
    "MA67": "Alert: Correction to a prior claim.",
    "MA68": "Alert: We did not crossover this claim because the secondary insurance information on the claim was incomplete.",
    "MA69": "Missing/incomplete/invalid remarks.",
    "MA70": "Missing/incomplete/invalid provider representative signature.",
    "MA71": "Missing/incomplete/invalid provider representative signature date.",
    "MA72": "Alert: The patient overpaid you for these assigned services. You must issue the patient a refund within 30 days.",
    "MA73": "Informational remittance associated with a Medicare demonstration. No payment issued under fee-for-service Medicare as patient has elected managed care.",
    "MA74": "Alert: This payment replaces an earlier payment for this claim that was either lost, damaged or returned.",
    "MA75": "Missing/incomplete/invalid patient or authorized representative signature.",
    "MA76": "Missing/incomplete/invalid provider identifier for home health agency or hospice when physician is performing care plan oversight services.",
    "MA77": "Alert: The patient overpaid you. You must issue the patient a refund within 30 days.",
    "MA79": "Billed in excess of interim rate.",
    "MA80": "Informational notice. No payment issued for this claim with this notice.",
    "MA81": "Missing/incomplete/invalid provider/supplier signature.",
    "MA83": "Did not indicate whether we are the primary or secondary payer.",
    "MA84": "Patient identified as participating in the National Emphysema Treatment Trial but our records indicate that this patient is either not a participant, or has not yet been approved for this phase of the study.",
    "MA88": "Missing/incomplete/invalid insured's address and/or telephone number for the primary payer.",
    "MA89": "Missing/incomplete/invalid patient's relationship to the insured for the primary payer.",
    "MA90": "Missing/incomplete/invalid employment status code for the primary insured.",
    "MA91": "Alert: This determination is the result of the appeal you filed.",
    "MA92": "Missing plan information for other insurance.",
    "MA93": "Non-PIP (Periodic Interim Payment) claim.",
    "MA94": "Did not enter the statement 'Attending physician not hospice employee' on the claim form.",
    "MA96": "Claim rejected. Coded as a Medicare Managed Care Demonstration but patient is not enrolled in a Medicare managed care plan.",
    "MA97": "Missing/incomplete/invalid Medicare Managed Care Demonstration contract number or clinical trial registry number.",
    "MA99": "Missing/incomplete/invalid Medigap information.",
    "MA100": "Missing/incomplete/invalid date of current illness or symptoms.",
    "MA103": "Hemophilia Add On.",
    "MA106": "PIP (Periodic Interim Payment) claim.",
    "MA107": "Paper claim contains more than three separate data items in field 19.",
    "MA108": "Paper claim contains more than one data item in field 23.",
    "MA109": "Claim processed in accordance with ambulatory surgical guidelines.",
    "MA110": "Missing/incomplete/invalid information on whether the diagnostic test(s) were performed by an outside entity or if no purchased tests are included on the claim.",
    "MA111": "Missing/incomplete/invalid purchase price of the test(s) and/or the performing laboratory's name and address.",
    "MA112": "Missing/incomplete/invalid group practice information.",
    "MA113": "Incomplete/invalid taxpayer identification number (TIN) submitted by you per the Internal Revenue Service.",
    "MA114": "Missing/incomplete/invalid information on where the services were furnished.",
    "MA115": "Missing/incomplete/invalid physical location (name and address, or PIN) where the service(s) were rendered in a Health Professional Shortage Area (HPSA).",
    "MA116": "Did not complete the statement 'Homebound' on the claim to validate whether laboratory services were performed at home or in an institution.",
    "MA117": "This claim has been assessed a $1.00 user fee.",
    "MA118": "Alert: No Medicare payment issued for this claim for services or supplies furnished to a Medicare-eligible veteran through a facility of the Department of Veterans Affairs.",
    "MA120": "Missing/incomplete/invalid CLIA certification number.",
    "MA121": "Missing/incomplete/invalid x-ray date.",
    "MA122": "Missing/incomplete/invalid initial treatment date.",
    "MA123": "Your center was not selected to participate in this study, therefore, we cannot pay for these services.",
    "MA125": "Per legislation governing this program, payment constitutes payment in full.",
    "MA126": "Pancreas transplant not covered unless kidney transplant performed.",
    "MA128": "Missing/incomplete/invalid FDA approval number.",
    "MA130": "Your claim contains incomplete and/or invalid information, and no appeal rights are afforded because the claim is unprocessable. Please submit a new claim with the complete/correct information.",
    "MA131": "Physician already paid for services in conjunction with this demonstration claim.",
    "MA132": "Adjustment to the pre-demonstration rate.",
    "MA133": "Claim overlaps inpatient stay. Rebill only those services rendered outside the inpatient stay.",
    "MA134": "Missing/incomplete/invalid provider number of the facility where the patient resides.",
    "N1": "Alert: You may appeal this decision in writing within the required time limits following receipt of this notice.",
    "N2": "This allowance has been made in accordance with the most appropriate course of treatment provision of the plan.",
    "N3": "Missing consent form.",
    "N4": "Missing/Incomplete/Invalid prior Insurance Carrier(s) EOB.",
    "N5": "EOB received from previous payer. Claim not on file.",
    "N6": "Under FEHB law, we cannot pay more for covered care than the amount Medicare would have allowed.",
    "N7": "Alert: Processing of this claim/service has included consideration under Major Medical provisions.",
    "N8": "Crossover claim denied by previous payer and complete claim data not forwarded. Resubmit this claim to this payer to provide adequate data for adjudication.",
    "N9": "Adjustment represents the estimated amount a previous payer may pay.",
    "N10": "Adjustment based on the findings of a review organization/professional consult/manual adjudication/medical advisor/dental advisor/peer review.",
    "N11": "Denial reversed because of medical review.",
    "N12": "Policy provides coverage supplemental to Medicare. As the member does not appear to be enrolled in the applicable part of Medicare, the member is responsible for payment.",
    "N13": "Payment based on professional/technical component modifier(s).",
    "N15": "Services for a newborn must be billed separately.",
    "N16": "Family/member Out-of-Pocket maximum has been met. Payment based on a higher percentage.",
    "N19": "Procedure code incidental to primary procedure.",
    "N20": "Service not payable with other service rendered on the same date.",
    "N21": "Alert: Your line item has been separated into multiple lines to expedite handling.",
    "N22": "Alert: This procedure code was added/changed because it more accurately describes the services rendered.",
    "N23": "Alert: Patient liability may be affected due to coordination of benefits with other carriers and/or maximum benefit provisions.",
    "N24": "Missing/incomplete/invalid Electronic Funds Transfer (EFT) banking information.",
    "N25": "This company has been contracted by your benefit plan to provide administrative claims payment services only.",
    "N26": "Missing itemized bill/statement.",
    "N27": "Missing/incomplete/invalid treatment number.",
    "N28": "Consent form requirements not fulfilled.",
    "N30": "Patient ineligible for this service.",
    "N31": "Missing/incomplete/invalid prescribing provider identifier.",
    "N32": "Claim must be submitted by the provider who rendered the service.",
    "N33": "No record of health check prior to initiation of treatment.",
    "N34": "Incorrect claim form/format for this service.",
    "N35": "Program integrity/utilization review decision.",
    "N36": "Claim must meet primary payer's processing requirements before we can consider payment.",
    "N37": "Missing/incomplete/invalid tooth number/letter.",
    "N39": "Procedure code is not compatible with tooth number/letter.",
    "N40": "Missing radiology film(s)/image(s).",
    "N42": "Missing mental health assessment.",
    "N43": "Bed hold or leave days exceeded.",
    "N45": "Payment based on authorized amount.",
    "N46": "Missing/incomplete/invalid admission hour.",
    "N47": "Claim conflicts with another inpatient stay.",
    "N48": "Claim information does not agree with information received from other insurance carrier.",
    "N49": "Court ordered coverage information needs validation.",
    "N50": "Missing/incomplete/invalid discharge information.",
    "N51": "Electronic interchange agreement not on file for provider/submitter.",
    "N52": "Patient not enrolled in the billing provider's managed care plan on the date of service.",
    "N53": "Missing/incomplete/invalid point of pick-up address.",
    "N54": "Claim information is inconsistent with pre-certified/authorized services.",
    "N55": "Procedures for billing with group/referring/performing providers were not followed.",
    "N56": "Procedure code billed is not correct/valid for the services billed or the date of service billed.",
    "N57": "Missing/incomplete/invalid prescribing date.",
    "N58": "Missing/incomplete/invalid patient liability amount.",
    "N59": "Alert: Please refer to your provider manual for additional program and provider information.",
    "N61": "Rebill services on separate claims.",
    "N62": "Dates of service span multiple rate periods. Resubmit separate claims.",
    "N63": "Rebill services on separate claim lines.",
    "N64": "The 'from' and 'to' dates must be different.",
    "N65": "Procedure code or procedure rate count cannot be determined, or was not on file, for the date of service/provider.",
    "N67": "Professional provider services not paid separately. Included in facility payment under a demonstration project.",
    "N68": "Prior payment being cancelled as we were subsequently notified this patient was covered by a demonstration project in this site of service.",
    "N69": "Alert: PPS (Prospective Payment System) code changed by claims processing system.",
    "N70": "Consolidated billing and payment applies.",
    "N71": "Your unassigned claim for a drug or biological, clinical diagnostic laboratory services or ambulance service was processed as an assigned claim.",
    "N72": "PPS (Prospective Payment System) code changed by medical reviewers. Not supported by clinical records.",
    "N74": "Resubmit with multiple claims, each claim covering services provided in only one calendar month.",
    "N75": "Missing/incomplete/invalid tooth surface information.",
    "N76": "Missing/incomplete/invalid number of riders.",
    "N77": "Missing/incomplete/invalid designated provider number.",
    "N78": "The necessary components of the child and teen checkup (EPSDT) were not completed.",
    "N79": "Service billed is not compatible with patient location information.",
    "N80": "Missing/incomplete/invalid prenatal screening information.",
    "N81": "Procedure billed is not compatible with tooth surface code.",
    "N82": "Provider must accept insurance payment as payment in full when a third party payer contract specifies full reimbursement.",
    "N83": "No appeal rights. Adjudicative decision based on the provisions of a demonstration project.",
    "N84": "Alert: Further installment payments are forthcoming.",
    "N85": "Alert: This is the final installment payment.",
    "N86": "A failed trial of pelvic muscle exercise training is required in order for biofeedback training for the treatment of urinary incontinence to be covered.",
    "N87": "Home use of biofeedback therapy is not covered.",
    "N88": "Alert: This payment is being made conditionally. An HHA episode of care notice has been filed for this patient.",
    "N89": "Alert: Payment information for this claim has been forwarded to more than one other payer.",
    "N90": "Covered only when performed by the attending physician.",
    "N91": "Services not included in the appeal review.",
    "N92": "This facility is not certified for digital mammography.",
    "N93": "A separate claim must be submitted for each place of service. Services furnished at multiple sites may not be billed in the same claim.",
    "N94": "Claim/Service denied because a more specific taxonomy code is required for adjudication.",
    "N95": "This provider type/provider specialty may not bill this service.",
    "N96": "Patient must be refractory to conventional therapy and be an appropriate surgical candidate such that implantation with anesthesia can occur.",
    "N97": "Patients with stress incontinence, urinary obstruction, and specific neurologic diseases which are associated with secondary manifestations are excluded.",
    "N98": "Patient must have had a successful test stimulation in order to support subsequent implantation.",
    "N99": "Patient must be able to demonstrate adequate ability to record voiding diary data.",
    "N103": "Records indicate this patient was a prisoner or in custody of a Federal, State, or local authority when the service was rendered.",
    "N104": "This claim/service is not payable under our claims jurisdiction area.",
    "N105": "This is a misdirected claim/service for an RRB beneficiary.",
    "N106": "Payment for services furnished to SNF inpatients can only be made to the SNF.",
    "N107": "Services furnished to SNF inpatients must be billed on the inpatient claim. They cannot be billed separately as outpatient services.",
    "N108": "Missing/incomplete/invalid upgrade information.",
    "N109": "Alert: This claim/service was chosen for complex review.",
    "N110": "This facility is not certified for film mammography.",
    "N111": "No appeal right except duplicate claim/service issue. This service was included in a claim that has been previously billed and adjudicated.",
    "N112": "This claim is excluded from your electronic remittance advice.",
    "N113": "Only one initial visit is covered per physician, group practice or provider.",
    "N114": "During the transition to the Ambulance Fee Schedule, payment is based on the lesser of a blended amount.",
    "N115": "This decision was based on a Local Coverage Determination (LCD).",
    "N116": "Alert: This payment is being made conditionally because the service was provided in the home.",
    "N117": "This service is paid only once in a patient's lifetime.",
    "N118": "This service is not paid if billed more than once every 28 days.",
    "N119": "This service is not paid if billed once every 28 days, and the patient has spent 5 or more consecutive days in any inpatient or SNF within those 28 days.",
    "N120": "Payment is subject to home health prospective payment system partial episode payment adjustment.",
    "N121": "Medicare Part B does not pay for items or services provided by this type of practitioner for beneficiaries in a Medicare Part A covered SNF stay.",
    "N122": "Add-on code cannot be billed by itself.",
    "N123": "Alert: This is a split service and represents a portion of the units from the originally submitted service.",
    "N124": "Payment has been denied for the/made only for a less extensive service/item because the information furnished does not substantiate the need for the more extensive service/item.",
    "N125": "Payment has been denied/made only for a less extensive service/item. If you have collected any amount from the patient, you must refund that amount to the patient within 30 days.",
    "N126": "Social Security Records indicate that this individual has been deported.",
    "N127": "This is a misdirected claim/service for a United Mine Workers of America (UMWA) beneficiary.",
    "N128": "This amount represents the prior to coverage portion of the allowance.",
    "N129": "Not eligible due to the patient's age.",
    "N130": "Consult plan benefit documents/guidelines for information about restrictions for this service.",
    "N131": "Total payments under multiple contracts cannot exceed the allowance for this service.",
    "N132": "Alert: Payments will cease for services rendered by this US Government debarred or excluded provider after the 30 day grace period.",
    "N133": "Alert: Services for predetermination and services requesting payment are being processed separately.",
    "N134": "Alert: This represents your scheduled payment for this service. If treatment has been discontinued, please contact Customer Service.",
    "N135": "Record fees are the patient's responsibility and limited to the specified co-payment.",
    "N141": "The patient was not residing in a long-term care facility during all or part of the service dates billed.",
    "N142": "The original claim was denied. Resubmit a new claim, not a replacement claim.",
    "N143": "The patient was not in a hospice program during all or part of the service dates billed.",
    "N144": "The rate changed during the dates of service billed.",
    "N146": "Missing screening document.",
    "N147": "Long term care case mix or per diem rate cannot be determined because the patient ID number is missing, incomplete, or invalid.",
    "N148": "Missing/incomplete/invalid date of last menstrual period.",
    "N149": "Rebill all applicable services on a single claim.",
    "N150": "Missing/incomplete/invalid model number.",
    "N151": "Telephone contact services will not be paid until the face-to-face contact requirement has been met.",
    "N152": "Missing/incomplete/invalid replacement claim information.",
    "N153": "Missing/incomplete/invalid room and board rate.",
    "N157": "Transportation to/from this destination is not covered.",
    "N158": "Transportation in a vehicle other than an ambulance is not covered.",
    "N159": "Payment denied/reduced because mileage is not covered when the patient is not in the ambulance.",
    "N160": "The patient must choose an option before a payment can be made for this procedure/equipment/supply/service.",
    "N161": "This drug/service/supply is covered only when the associated service is covered.",
    "N163": "Medical record does not support code billed per the code definition.",
    "N167": "Charges exceed the post-transplant coverage limit.",
    "N170": "A new/revised/renewed certificate of medical necessity is needed.",
    "N171": "Payment for repair or replacement is not covered or has exceeded the purchase price.",
    "N172": "The patient is not liable for the denied/adjusted charge(s) for receiving any updated service/item.",
    "N173": "No qualifying hospital stay dates were provided for this episode of care.",
    "N174": "This is not a covered service/procedure/equipment/bed, however patient liability is limited to amounts shown in the adjustments under group 'PR'.",
    "N175": "Missing review organization approval.",
    "N176": "Services provided aboard a ship are covered only when the ship is of United States registry and is in United States waters.",
    "N177": "Alert: We did not send this claim to patient's other insurer. They have indicated no additional payment can be made.",
    "N178": "Missing pre-operative images/visual field results.",
    "N179": "Additional information has been requested from the member. The charges will be reconsidered upon receipt of that information.",
    "N180": "This item or service does not meet the criteria for the category under which it was billed.",
    "N181": "Additional information is required from another provider involved in this service.",
    "N182": "This claim/service must be billed according to the schedule for this plan.",
    "N183": "Alert: This is a predetermination advisory message, when this service is submitted for payment additional documentation as specified in plan documents will be required.",
    "N184": "Rebill technical and professional components separately.",
    "N185": "Alert: Do not resubmit this claim/service.",
    "N186": "Non-Availability Statement (NAS) required for this service. Contact the nearest Military Treatment Facility (MTF) for assistance.",
    "N188": "The approved level of care does not match the procedure code submitted.",
    "N191": "The provider must update insurance information directly with payer.",
    "N192": "Alert: Patient is a Medicaid/Qualified Medicare Beneficiary.",
    "N193": "Alert: Specific federal/state/local program may cover this service through another payer.",
    "N194": "Technical component not paid if provider does not own the equipment used.",
    "N195": "The technical component must be billed separately.",
    "N196": "Alert: Patient eligible to apply for other coverage which may be primary.",
    "N197": "The subscriber must update insurance information directly with payer.",
    "N198": "Rendering provider must be affiliated with the pay-to provider.",
    "N199": "Additional payment/recoupment approved based on payer-initiated review/audit.",
    "N200": "The professional component must be billed separately.",
    "N202": "Alert: Additional information/explanation will be sent separately.",
    "N203": "Missing/incomplete/invalid anesthesia time/units.",
    "N204": "Services under review for possible pre-existing condition. Send medical records for prior 12 months.",
    "N205": "Information provided was illegible.",
    "N206": "The supporting documentation does not match the information sent on the claim.",
    "N207": "Missing/incomplete/invalid weight.",
    "N208": "Missing/incomplete/invalid DRG code.",
    "N209": "Missing/incomplete/invalid taxpayer identification number (TIN).",
    "N210": "Alert: You may appeal this decision.",
    "N211": "Alert: You may not appeal this decision.",
    "N212": "Charges processed under a Point of Service benefit.",
    "N213": "Missing/incomplete/invalid facility/discrete unit DRG/DRG exempt status information.",
    "N214": "Missing/incomplete/invalid history of the related initial surgical procedure(s).",
    "N216": "We do not offer coverage for this type of service or the patient is not enrolled in this portion of our benefit package.",
    "N217": "We pay only one site of service per provider per claim.",
    "N218": "You must furnish and service this item for as long as the patient continues to need it.",
    "N219": "Payment based on previous payer's allowed amount.",
    "N220": "Alert: See the payer's web site or contact the payer's Customer Service department to obtain forms and instructions for filing a provider dispute.",
    "N221": "Missing Admitting History and Physical report.",
    "N222": "Incomplete/invalid Admitting History and Physical report.",
    "N223": "Missing documentation of benefit to the patient during initial treatment period.",
    "N224": "Incomplete/invalid documentation of benefit to the patient during initial treatment period.",
    "N226": "Incomplete/invalid American Diabetes Association Certificate of Recognition.",
    "N227": "Incomplete/invalid Certificate of Medical Necessity.",
    "N228": "Incomplete/invalid consent form.",
    "N229": "Incomplete/invalid contract indicator.",
    "N230": "Incomplete/invalid indication of whether the patient owns the equipment that requires the part or supply.",
    "N231": "Incomplete/invalid invoice or statement certifying the actual cost of the lens.",
    "N232": "Incomplete/invalid itemized bill/statement.",
    "N233": "Incomplete/invalid operative note/report.",
    "N234": "Incomplete/invalid oxygen certification/re-certification.",
    "N235": "Incomplete/invalid pacemaker registration form.",
    "N236": "Incomplete/invalid pathology report.",
    "N237": "Incomplete/invalid patient medical record for this service.",
    "N238": "Incomplete/invalid physician certified plan of care.",
    "N239": "Incomplete/invalid physician financial relationship form.",
    "N240": "Incomplete/invalid radiology report.",
    "N241": "Incomplete/invalid review organization approval.",
    "N242": "Incomplete/invalid radiology film(s)/image(s).",
    "N243": "Incomplete/invalid/not approved screening document.",
    "N244": "Incomplete/Invalid pre-operative images/visual field results.",
    "N245": "Incomplete/invalid plan information for other insurance.",
    "N246": "State regulated patient payment limitations apply to this service.",
    "N247": "Missing/incomplete/invalid assistant surgeon taxonomy.",
    "N248": "Missing/incomplete/invalid assistant surgeon name.",
    "N249": "Missing/incomplete/invalid assistant surgeon primary identifier.",
    "N250": "Missing/incomplete/invalid assistant surgeon secondary identifier.",
    "N251": "Missing/incomplete/invalid attending provider taxonomy.",
    "N252": "Missing/incomplete/invalid attending provider name.",
    "N253": "Missing/incomplete/invalid attending provider primary identifier.",
    "N254": "Missing/incomplete/invalid attending provider secondary identifier.",
    "N255": "Missing/incomplete/invalid billing provider taxonomy.",
    "N256": "Missing/incomplete/invalid billing provider/supplier name.",
    "N257": "Missing/incomplete/invalid billing provider/supplier primary identifier.",
    "N258": "Missing/incomplete/invalid billing provider/supplier address.",
    "N259": "Missing/incomplete/invalid billing provider/supplier secondary identifier.",
    "N260": "Missing/incomplete/invalid billing provider/supplier contact information.",
    "N261": "Missing/incomplete/invalid operating provider name.",
    "N262": "Missing/incomplete/invalid operating provider primary identifier.",
    "N263": "Missing/incomplete/invalid operating provider secondary identifier.",
    "N264": "Missing/incomplete/invalid ordering provider name.",
    "N265": "Missing/incomplete/invalid ordering provider primary identifier.",
    "N266": "Missing/incomplete/invalid ordering provider address.",
    "N267": "Missing/incomplete/invalid ordering provider secondary identifier.",
    "N268": "Missing/incomplete/invalid ordering provider contact information.",
    "N269": "Missing/incomplete/invalid other provider name.",
    "N270": "Missing/incomplete/invalid other provider primary identifier.",
    "N271": "Missing/incomplete/invalid other provider secondary identifier.",
    "N272": "Missing/incomplete/invalid other payer attending provider identifier.",
    "N273": "Missing/incomplete/invalid other payer operating provider identifier.",
    "N274": "Missing/incomplete/invalid other payer other provider identifier.",
    "N275": "Missing/incomplete/invalid other payer purchased service provider identifier.",
    "N276": "Missing/incomplete/invalid other payer referring provider identifier.",
    "N277": "Missing/incomplete/invalid other payer rendering provider identifier.",
    "N278": "Missing/incomplete/invalid other payer service facility provider identifier.",
    "N279": "Missing/incomplete/invalid pay-to provider name.",
    "N280": "Missing/incomplete/invalid pay-to provider primary identifier.",
    "N281": "Missing/incomplete/invalid pay-to provider address.",
    "N282": "Missing/incomplete/invalid pay-to provider secondary identifier.",
    "N283": "Missing/incomplete/invalid purchased service provider identifier.",
    "N284": "Missing/incomplete/invalid referring provider taxonomy.",
    "N285": "Missing/incomplete/invalid referring provider name.",
    "N286": "Missing/incomplete/invalid referring provider primary identifier.",
    "N287": "Missing/incomplete/invalid referring provider secondary identifier.",
    "N288": "Missing/incomplete/invalid rendering provider taxonomy.",
    "N289": "Missing/incomplete/invalid rendering provider name.",
    "N290": "Missing/incomplete/invalid rendering provider primary identifier.",
    "N291": "Missing/incomplete/invalid rendering provider secondary identifier.",
    "N292": "Missing/incomplete/invalid service facility name.",
    "N293": "Missing/incomplete/invalid service facility primary identifier.",
    "N294": "Missing/incomplete/invalid service facility primary address.",
    "N295": "Missing/incomplete/invalid service facility secondary identifier.",
    "N296": "Missing/incomplete/invalid supervising provider name.",
    "N297": "Missing/incomplete/invalid supervising provider primary identifier.",
    "N298": "Missing/incomplete/invalid supervising provider secondary identifier.",
    "N299": "Missing/incomplete/invalid occurrence date(s).",
    "N300": "Missing/incomplete/invalid occurrence span date(s).",
    "N301": "Missing/incomplete/invalid procedure date(s).",
    "N302": "Missing/incomplete/invalid other procedure date(s).",
    "N303": "Missing/incomplete/invalid principal procedure date.",
    "N304": "Missing/incomplete/invalid dispensed date.",
    "N305": "Missing/incomplete/invalid injury/accident date.",
    "N306": "Missing/incomplete/invalid acute manifestation date.",
    "N307": "Missing/incomplete/invalid adjudication or payment date.",
    "N308": "Missing/incomplete/invalid appliance placement date.",
    "N309": "Missing/incomplete/invalid assessment date.",
    "N310": "Missing/incomplete/invalid assumed or relinquished care date.",
    "N311": "Missing/incomplete/invalid authorized to return to work date.",
    "N312": "Missing/incomplete/invalid begin therapy date.",
    "N313": "Missing/incomplete/invalid certification revision date.",
    "N314": "Missing/incomplete/invalid diagnosis date.",
    "N315": "Missing/incomplete/invalid disability from date.",
    "N316": "Missing/incomplete/invalid disability to date.",
    "N317": "Missing/incomplete/invalid discharge hour.",
    "N318": "Missing/incomplete/invalid discharge or end of care date.",
    "N319": "Missing/incomplete/invalid hearing or vision prescription date.",
    "N320": "Missing/incomplete/invalid Home Health Certification Period.",
    "N321": "Missing/incomplete/invalid last admission period.",
    "N322": "Missing/incomplete/invalid last certification date.",
    "N323": "Missing/incomplete/invalid last contact date.",
    "N324": "Missing/incomplete/invalid last seen/visit date.",
    "N325": "Missing/incomplete/invalid last worked date.",
    "N326": "Missing/incomplete/invalid last x-ray date.",
    "N327": "Missing/incomplete/invalid other insured birth date.",
    "N328": "Missing/incomplete/invalid Oxygen Saturation Test date.",
    "N329": "Missing/incomplete/invalid patient birth date.",
    "N330": "Missing/incomplete/invalid patient death date.",
    "N331": "Missing/incomplete/invalid physician order date.",
    "N332": "Missing/incomplete/invalid prior hospital discharge date.",
    "N333": "Missing/incomplete/invalid prior placement date.",
    "N334": "Missing/incomplete/invalid re-evaluation date.",
    "N335": "Missing/incomplete/invalid referral date.",
    "N336": "Missing/incomplete/invalid replacement date.",
    "N337": "Missing/incomplete/invalid secondary diagnosis date.",
    "N338": "Missing/incomplete/invalid shipped date.",
    "N339": "Missing/incomplete/invalid similar illness or symptom date.",
    "N340": "Missing/incomplete/invalid subscriber birth date.",
    "N341": "Missing/incomplete/invalid surgery date.",
    "N342": "Missing/incomplete/invalid test performed date.",
    "N343": "Missing/incomplete/invalid Transcutaneous Electrical Nerve Stimulator (TENS) trial start date.",
    "N344": "Missing/incomplete/invalid Transcutaneous Electrical Nerve Stimulator (TENS) trial end date.",
    "N345": "Date range not valid with units submitted.",
    "N346": "Missing/incomplete/invalid oral cavity designation code.",
    "N347": "Your claim for a referred or purchased service cannot be paid because payment has already been made for this same service to another provider.",
    "N348": "You chose that this service/supply/drug would be rendered/supplied and billed by a different practitioner/supplier.",
    "N349": "The administration method and drug must be reported to adjudicate this service.",
    "N350": "Missing/incomplete/invalid description of service for a Not Otherwise Classified (NOC) code or for an Unlisted/By Report procedure.",
    "N351": "Service date outside of the approved treatment plan service dates.",
    "N352": "Alert: There are no scheduled payments for this service. Submit a claim for each patient visit.",
    "N353": "Alert: Benefits have been estimated, when the actual services have been rendered, additional payment will be considered based on the submitted claim.",
    "N354": "Incomplete/invalid invoice.",
    "N356": "Not covered when performed with, or subsequent to, a non-covered service.",
    "N357": "Time frame requirements between this service/procedure/supply and a related service/procedure/supply have not been met.",
    "N358": "Alert: This decision may be reviewed if additional documentation as described in the contract or plan benefit documents is submitted.",
    "N359": "Missing/incomplete/invalid height.",
    "N362": "The number of Days or Units of Service exceeds our acceptable maximum.",
    "N363": "Alert: in the near future we are implementing new policies/procedures that would affect this determination.",
    "N364": "Alert: According to our agreement, you must waive the deductible and/or coinsurance amounts.",
    "N366": "Requested information not provided. The claim will be reopened if the information previously requested is submitted within one year after the date of this denial notice.",
    "N367": "Alert: The claim information has been forwarded to a Consumer Spending Account processor for review.",
    "N368": "You must appeal the determination of the previously adjudicated claim.",
    "N369": "Alert: Although this claim has been processed, it is deficient according to state legislation/regulation.",
    "N370": "Billing exceeds the rental months covered/approved by the payer.",
    "N371": "Alert: Title of this equipment must be transferred to the patient.",
    "N372": "Only reasonable and necessary maintenance/service charges are covered.",
    "N373": "It has been determined that another payer paid the services as primary when they were not the primary payer.",
    "N374": "Primary Medicare Part A insurance has been exhausted and a Part B Remittance Advice is required.",
    "N375": "Missing/incomplete/invalid questionnaire/information required to determine dependent eligibility.",
    "N376": "Subscriber/patient is assigned to active military duty, therefore primary coverage may be TRICARE.",
    "N377": "Payment based on a processed replacement claim.",
    "N378": "Missing/incomplete/invalid prescription quantity.",
    "N379": "Claim level information does not match line level information.",
    "N380": "The original claim has been processed, submit a corrected claim.",
    "N381": "Alert: Consult our contractual agreement for restrictions/billing/payment information related to these charges.",
    "N382": "Missing/incomplete/invalid patient identifier.",
    "N383": "Not covered when deemed cosmetic.",
    "N384": "Records indicate that the referenced body part/tooth has been removed in a previous procedure.",
    "N385": "Notification of admission was not timely according to published plan procedures.",
    "N386": "This decision was based on a National Coverage Determination (NCD).",
    "N387": "Alert: Submit this claim to the patient's other insurer for potential payment of supplemental benefits. We did not forward the claim information.",
    "N388": "Missing/incomplete/invalid prescription number.",
    "N389": "Duplicate prescription number submitted.",
    "N390": "This service/report cannot be billed separately.",
    "N391": "Missing emergency department records.",
    "N392": "Incomplete/invalid emergency department records.",
    "N393": "Missing progress notes/report.",
    "N394": "Incomplete/invalid progress notes/report.",
    "N395": "Missing laboratory report.",
    "N396": "Incomplete/invalid laboratory report.",
    "N397": "Benefits are not available for incomplete service(s)/undelivered item(s).",
    "N398": "Missing elective consent form.",
    "N399": "Incomplete/invalid elective consent form.",
    "N400": "Alert: Electronically enabled providers should submit claims electronically.",
    "N401": "Missing periodontal charting.",
    "N402": "Incomplete/invalid periodontal charting.",
    "N403": "Missing facility certification.",
    "N404": "Incomplete/invalid facility certification.",
    "N405": "This service is only covered when the donor's insurer(s) do not provide coverage for the service.",
    "N406": "This service is only covered when the recipient's insurer(s) do not provide coverage for the service.",
    "N407": "You are not an approved submitter for this transmission format.",
    "N408": "This payer does not cover deductibles assessed by a previous payer.",
    "N409": "This service is related to an accidental injury and is not covered unless provided within a specific time frame from the date of the accident.",
    "N410": "Not covered unless the prescription changes.",
    "N411": "This service is allowed one time in a 6-month period.",
    "N412": "This service is allowed 2 times in a 12-month period.",
    "N413": "This service is allowed 2 times in a benefit year.",
    "N414": "This service is allowed 4 times in a 12-month period.",
    "N415": "This service is allowed 1 time in an 18-month period.",
    "N416": "This service is allowed 1 time in a 3-year period.",
    "N417": "This service is allowed 1 time in a 5-year period.",
    "N418": "Misrouted claim. See the payer's claim submission instructions.",
    "N419": "Claim payment was the result of a payer's retroactive adjustment due to a retroactive rate change.",
    "N420": "Claim payment was the result of a payer's retroactive adjustment due to a Coordination of Benefits or Third Party Liability Recovery.",
    "N421": "Claim payment was the result of a payer's retroactive adjustment due to a review organization decision.",
    "N422": "Claim payment was the result of a payer's retroactive adjustment due to a payer's contract incentive program.",
    "N423": "Claim payment was the result of a payer's retroactive adjustment due to a non standard program.",
    "N424": "Patient does not reside in the geographic area required for this type of payment.",
    "N425": "Statutorily excluded service(s).",
    "N426": "No coverage when self-administered.",
    "N427": "Payment for eyeglasses or contact lenses can be made only after cataract surgery.",
    "N428": "Not covered when performed in this place of service.",
    "N429": "Not covered when considered routine.",
    "N430": "Procedure code is inconsistent with the units billed.",
    "N431": "Not covered with this procedure.",
    "N432": "Alert: Adjustment based on a Recovery Audit.",
    "N433": "Resubmit this claim using only your National Provider Identifier (NPI).",
    "N434": "Missing/Incomplete/Invalid Present on Admission indicator.",
    "N435": "Exceeds number/frequency approved/allowed within time period without support documentation.",
    "N436": "The injury claim has not been accepted and a mandatory medical reimbursement has been made.",
    "N437": "Alert: If the injury claim is accepted, these charges will be reconsidered.",
    "N438": "This jurisdiction only accepts paper claims.",
    "N439": "Missing anesthesia physical status report/indicators.",
    "N440": "Incomplete/invalid anesthesia physical status report/indicators.",
    "N441": "This missed/cancelled appointment is not covered.",
    "N442": "Payment based on an alternate fee schedule.",
    "N443": "Missing/incomplete/invalid total time or begin/end time.",
    "N445": "Missing document for actual cost or paid amount.",
    "N446": "Incomplete/invalid document for actual cost or paid amount.",
    "N447": "Payment is based on a generic equivalent as required documentation was not provided.",
    "N448": "This drug/service/supply is not included in the fee schedule or contracted/legislated fee arrangement.",
    "N449": "Payment based on a comparable drug/service/supply.",
    "N450": "Covered only when performed by the primary treating physician or the designee.",
    "N451": "Missing Admission Summary Report.",
    "N452": "Incomplete/invalid Admission Summary Report.",
    "N453": "Missing Consultation Report.",
    "N454": "Incomplete/invalid Consultation Report.",
    "N455": "Missing Physician Order.",
    "N456": "Incomplete/invalid Physician Order.",
    "N457": "Missing Diagnostic Report.",
    "N458": "Incomplete/invalid Diagnostic Report.",
    "N459": "Missing Discharge Summary.",
    "N460": "Incomplete/invalid Discharge Summary.",
    "N461": "Missing Nursing Notes.",
    "N462": "Incomplete/invalid Nursing Notes.",
    "N463": "Missing support data for claim.",
    "N464": "Incomplete/invalid support data for claim.",
    "N465": "Missing Physical Therapy Notes/Report.",
    "N466": "Incomplete/invalid Physical Therapy Notes/Report.",
    "N467": "Missing Tests and Analysis Report.",
    "N468": "Incomplete/invalid Report of Tests and Analysis Report.",
    "N469": "Alert: Claim/Service(s) subject to appeal process.",
    "N470": "This payment will complete the mandatory medical reimbursement limit.",
    "N471": "Missing/incomplete/invalid HIPPS Rate Code.",
    "N472": "Payment for this service has been issued to another provider.",
    "N473": "Missing certification.",
    "N474": "Incomplete/invalid certification.",
    "N475": "Missing completed referral form.",
    "N476": "Incomplete/invalid completed referral form.",
    "N477": "Missing Dental Models.",
    "N478": "Incomplete/invalid Dental Models.",
    "N479": "Missing Explanation of Benefits (Coordination of Benefits or Medicare Secondary Payer).",
    "N480": "Incomplete/invalid Explanation of Benefits (Coordination of Benefits or Medicare Secondary Payer).",
    "N481": "Missing Models.",
    "N482": "Incomplete/invalid Models.",
    "N485": "Missing Physical Therapy Certification.",
    "N486": "Incomplete/invalid Physical Therapy Certification.",
    "N487": "Missing Prosthetics or Orthotics Certification.",
    "N488": "Incomplete/invalid Prosthetics or Orthotics Certification.",
    "N489": "Missing referral form.",
    "N490": "Incomplete/invalid referral form.",
    "N491": "Missing/Incomplete/Invalid Exclusionary Rider Condition.",
    "N492": "Alert: A network provider may bill the member for this service if the member requested the service and agreed in writing, prior to receiving the service, to be financially responsible for the billed charge.",
    "N493": "Missing Doctor First Report of Injury.",
    "N494": "Incomplete/invalid Doctor First Report of Injury.",
    "N495": "Missing Supplemental Medical Report.",
    "N496": "Incomplete/invalid Supplemental Medical Report.",
    "N497": "Missing Medical Permanent Impairment or Disability Report.",
    "N498": "Incomplete/invalid Medical Permanent Impairment or Disability Report.",
    "N499": "Missing Medical Legal Report.",
    "N500": "Incomplete/invalid Medical Legal Report.",
    "N501": "Missing Vocational Report.",
    "N502": "Incomplete/invalid Vocational Report.",
    "N503": "Missing Work Status Report.",
    "N504": "Incomplete/invalid Work Status Report.",
    "N507": "Plan distance requirements have not been met.",
    "N516": "Records indicate a mismatch between the submitted NPI and EIN.",
    "N517": "Resubmit a new claim with the requested information.",
    "N518": "No separate payment for accessories when furnished for use with oxygen equipment.",
    "N519": "Invalid combination of HCPCS modifiers.",
    "N521": "Mismatch between the submitted provider information and the provider information stored in our system.",
    "N522": "Duplicate of a claim processed, or to be processed, as a crossover claim.",
    "N523": "The limitation on outlier payments defined by this payer for this service period has been met.",
    "N524": "Based on policy this payment constitutes payment in full.",
    "N525": "These services are not covered when performed within the global period of another service.",
    "N534": "This is an individual policy, the employer does not participate in plan sponsorship.",
    "N535": "Payment is adjusted when procedure is performed in this place of service based on the submitted procedure code and place of service.",
    "N537": "We have examined claims history and no records of the services have been found.",
    "N541": "Mismatch between the submitted insurance type code and the information stored in our system.",
    "N542": "Missing income verification.",
    "N543": "Incomplete/invalid income verification.",
    "N548": "Alert: Patient's calendar year deductible has been met.",
    "N549": "Alert: Patient's calendar year out-of-pocket maximum has been met.",
    "N554": "Missing/Incomplete/Invalid Family Planning Indicator.",
    "N555": "Missing medication list.",
    "N556": "Incomplete/invalid medication list.",
    "N563": "Alert: Missing required provider/supplier issuance of advance patient notice of non-coverage. The patient is not liable for payment for this service.",
    "N564": "Patient did not meet the inclusion criteria for the demonstration project or pilot program.",
    "N565": "Alert: This non-payable reporting code requires a modifier.",
    "N567": "Not covered when considered preventative.",
    "N569": "Not covered when performed for the reported diagnosis.",
    "N574": "Our records indicate the ordering/referring provider is of a type/specialty that cannot order or refer.",
    "N575": "Mismatch between the submitted ordering/referring provider name and the ordering/referring provider name stored in our records.",
    "N576": "Services not related to the specific incident/claim/accident/loss being reported.",
    "N580": "Determination based on the provisions of the insurance policy.",
    "N581": "Investigation of coverage eligibility is pending.",
    "N582": "Benefits suspended pending the patient's cooperation.",
    "N583": "Patient was not an occupant of our insured vehicle and therefore, is not an eligible injured person.",
    "N584": "Not covered based on the insured's noncompliance with policy or statutory conditions.",
    "N585": "Benefits are no longer available based on a final injury settlement.",
    "N586": "The injured party does not qualify for benefits.",
    "N587": "Policy benefits have been exhausted.",
    "N588": "The patient has instructed that medical claims/bills are not to be paid.",
    "N590": "Missing independent medical exam detailing the cause of injuries sustained and medical necessity of services rendered.",
    "N607": "Service provided for non-compensable condition(s).",
    "N611": "Claim in litigation. Contact insurer for more information.",
    "N619": "Coverage terminated for non-payment of premium.",
    "N622": "Not covered based on the date of injury/accident.",
    "N623": "Not covered when deemed unscientific/unproven/outmoded/experimental/excessive/inappropriate.",
    "N630": "Referral not authorized by attending physician.",
    "N636": "Adjusted because this is reimbursable only once per injury.",
    "N640": "Exceeds number/frequency approved/allowed within time period.",
    "N661": "Documentation does not support that the services rendered were medically necessary.",
    "N667": "Missing prescription.",
    "N668": "Incomplete/invalid prescription.",
    "N674": "Not covered unless a pre-requisite procedure/service has been provided.",
    "N699": "Payment adjusted based on the Physician Quality Reporting System (PQRS) Incentive Program.",
    "N700": "Payment adjusted based on the Electronic Health Records (EHR) Incentive Program.",
    "N701": "Payment adjusted based on the Value-based Payment Modifier.",
    "N702": "Decision based on review of previously adjudicated claims or for claims in process for the same/similar type of services.",
    "N703": "This service is incompatible with previously adjudicated claims or claims in process.",
    "N705": "Incomplete/invalid documentation.",
    "N706": "Missing documentation.",
    "N707": "Incomplete/invalid orders.",
    "N708": "Missing orders.",
    "N709": "Incomplete/invalid notes.",
    "N710": "Missing notes.",
    "N711": "Incomplete/invalid summary.",
    "N712": "Missing summary.",
    "N713": "Incomplete/invalid report.",
    "N714": "Missing report.",
    "N715": "Incomplete/invalid chart.",
    "N716": "Missing chart.",
    "N717": "Incomplete/Invalid documentation of face-to-face examination.",
    "N718": "Missing documentation of face-to-face examination.",
    "N729": "Missing patient medical/dental record for this service.",
    "N730": "Incomplete/invalid patient medical/dental record for this service.",
    "N737": "Missing Sleep Study Report.",
    "N739": "Missing Vein Study Report.",
    "N745": "Missing Ambulance Report.",
    "N749": "Missing Blood Gas Report.",
    "N752": "Missing/incomplete/invalid HIPPS Treatment Authorization Code (TAC).",
    "N753": "Missing/incomplete/invalid Attachment Control Number.",
    "N755": "Missing/incomplete/invalid ICD Indicator.",
    "N760": "This facility is not authorized to receive payment for the service(s).",
    "N761": "This provider is not authorized to receive payment for the service(s).",
    "N767": "The Medicaid state requires provider to be enrolled in the member's Medicaid state program prior to any claim benefits being processed.",
    "N771": "Alert: Under Federal law you cannot charge more than the limiting charge amount.",
    "N776": "This service is not a covered Telehealth service.",
    "N779": "Replacement/Void claims cannot be submitted until the original claim has finalized.",
    "N784": "Missing comprehensive procedure code.",
    "N790": "Provider/supplier not accredited for product/service.",
    "N791": "Missing history & physical report.",
    "N792": "Incomplete/invalid history & physical report.",
    "N795": "Item must be resubmitted as a purchase.",
    "N798": "Submit a void request for the original claim and resubmit a new claim.",
    "N800": "Only one service date is allowed per claim.",
    "N808": "Not covered for this provider type/provider specialty.",
    "N818": "Claims Dates of Service do not match Electronic Visit Verification System.",
    "N822": "Missing procedure modifier(s).",
    "N823": "Incomplete/Invalid procedure modifier(s).",
    "N831": "You have not responded to requests to revalidate your provider/supplier enrollment information.",
    "N836": "Provider W9 or Payee Registration not on file.",
    "N850": "Missing/incomplete/invalid narrative explaining/describing this service/treatment.",
    "N851": "Payment reduced because services were furnished by a therapy assistant.",
    "N857": "This claim has been adjusted/reversed. Refund any collected copayment to the member.",
    "N880": "Original claim closed due to changes in submitted data. Adjustment claim will be processed under a new claim number.",
    "N886": "Alert: A Health Care Claim Request for Additional Information (277 RFAI) has been sent.",
    "N888": "Alert: An electronic request for additional information has been sent for this claim.",
    "N891": "The maximum allowable payment for this service/procedure was paid by the primary insurance. No further payment due.",
    "N899": "Missing Initial Evaluation Report.",
    "N900": "Missing Therapy Notes/Report.",
    "N901": "Incomplete/Invalid Therapy Notes/Report.",
    "N902": "Missing Health Risk Assessment (HRA).",
    "N903": "Incomplete/Invalid Health Risk Assessment (HRA).",
    "N919": "Family/member out-of-pocket maximum has been met.",
    "N921": "The time limit for filing a reconsideration or appeal has expired.",
    "N922": "Missing primary care dentist information.",
}


def get_carc_meaning(carc_code):
    """Look up plain-English meaning for a CARC code."""
    return CARC_CODES.get(str(carc_code).strip().upper(), "CARC code not found in lookup table.")


def get_rarc_meaning(rarc_code):
    """Look up plain-English meaning for a RARC code."""
    if not rarc_code or rarc_code == "UNKNOWN":
        return "No remark code provided."
    return RARC_CODES.get(str(rarc_code).strip().upper(), "RARC code not found in lookup table.")


def get_code_meanings(carc_code, rarc_code):
    """Return both CARC and RARC meanings as a dict."""
    return {
        "carc_meaning": get_carc_meaning(carc_code),
        "rarc_meaning": get_rarc_meaning(rarc_code)
    }


if __name__ == "__main__":
    test_cases = [
        ("16", "MA130"),
        ("50", "N20"),
        ("97", "M15"),
        ("1", "N4"),
        ("96", "N180"),
        ("4", "N130"),
    ]
    print("Code Lookup Test:\n")
    for carc, rarc in test_cases:
        meanings = get_code_meanings(carc, rarc)
        print(f"CARC {carc}: {meanings['carc_meaning']}")
        print(f"RARC {rarc}: {meanings['rarc_meaning']}")
        print()